[env]
term = "xterm-256color"

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Thin" }
size = 16

[mouse]
hide_when_typing = true

[colors.primary]
background = "#101010"
